config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'welcome/index'

 root 'welcome#index' # !!Mueve el path a la vista del controlador WelcomeController
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions

end

app/models/branch.rb
class Branch < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Se va pluralizar el nombre de Employee = employees
  # Campos => employee.nombre (metodo del modelo) => devuelbe nombre del empleado
end

app/models/enterprise.rb
class Enterprise < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :name

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :nombre
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

      # def new #define un accion ap crear un nuevo usuario
      # end
def create
   user = User.authenticate(params[:email], params[:password])
       if user
         session[:user_id] = user.id
         redirect_to root_path, :notice => "Sesion iniciada!!"
      else
         flash.now.alert = "Invalid email or password"
         render "new"
      end
end

    def destroy
      session[:user_id] = nil
      redirect_to new_session_path :notice => "Sesion finalizada"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def index
  #
  # end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to 'welcome#index', :notice => "Sign UP!!"
    else
      render "new"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prueba</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>
<body>
  <header>
    <nav class="be-blue white large-padding" >
      <ul class="no-list row center-xs">
        <li class="col-md no-margin">
          <h1 class="no-margin" id="logo">Docdigitales</h1>
        </li>
        <li class="col-md">
          <%= link_to "inicio", root_path %>
        </li>
        <li class="col-md">
          Empresas
        </li>
        <li class="col-md">
          Empleados
        </li>
        <!-- <div id="user_nav"> -->
        <li class="col-md center-xs">
          <% if current_user %>
            Sesion iniciada como: <%= current_user.email %>.
            <li>
              <%= link_to "Cerrar sesion", log_out_path %>
            </li>
          <% else %>
            <%= link_to "Registrate!!", sign_up_path %> o
            <%= link_to "Inicia Sesion", log_in_path %>
          <% end %>
        </li>
        <!-- </div> -->

        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
      </ul>
    </nav>
  </header>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
  <div class="col-xs-8 col-md-6">
    <div class="row center-xs">
      <div class="box">

          <h1>Registro</h1>
          <%= form_for @user do |f| %>
            <% if @user.errors.any? %>
              <div class="be-blue">
                <h2>Form is invalid</h2>
                <ul>
                  <% for message in @user.errors.full_messages %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <!-- <div class="field">
              <%= f.label :nombre %>
              <%= f.text_field :nombre, class:"form-control" %>
            </div> -->
            <div class="field">
              <%= f.label :email %>
              <%= f.text_field :email, class:"form-control" %>
            </div>
            <div class="field">
              <%= f.label :password %>
              <%= f.password_field :password, class:"form-control"%>
            </div>
            <div class="field">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, class:"form-control" %>
            </div>

            <p class="btn be-blue"><%= f.submit %></p>

      <% end %>
     </div>
   </div>
 </div>

app/views/welcome/index.html.erb
<h1>Aplicacion prueba Rails docdigitales</h1>

<!-- <% if :user_id == true %>
    <h1> Bienvenido <%= current_user.email %><h1>
<% else %>
      	<h1> hasta luego!!!</h1
<% end %> -->
<% if current_user.present? %>
    <h1> Bienvenido <%= current_user.email %><h1>
  <% else %>
    <%= link_to 'Login', root_path %>
<% end %>